### ISSUE TITLE
some special characters missing during conversion

### ISSUE THREAD

**Issue by bjornstenger** [yanncoupin/stl2srt#4]
reason: entries in the "direct_mapping" dictionary are no longer continuously numbered from key "0xe0" ("Ohm"). It's easily fixed, use character encoding from wikipedia page:
https://en.wikipedia.org/wiki/ISO/IEC_6937

**Comment by yanncoupin** [comment]
Somebody else noticed the problem and made a pull request (which I missed). So after 3 years of (unintentionally) ignoring your issue, it's fixed...
